# ---------------------------------------- #
#  _        _                          __  #
# | |_ __ _| | _____   ___ ___  _ __  / _| #
# | __/ _` | |/ / _ \ / __/ _ \| '_ \| |_  #
# | || (_| |   <  __/| (_| (_) | | | |  _| #
#  \__\__,_|_|\_\___(_)___\___/|_| |_|_|   #
#                                          #
# ---------------------------------------- #


# ENVIRONMENT SECTION #

export ZDOTDIR="$HOME/.config/zsh"
export EDITOR="nvim"


# XDG PATHS SECTION #

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share


# FEH SECTION #

feh --bg-scale "$HOME/.config/wallpapers/itachi-wallpaper.png"


# I3 SECTION #

exec i3
